### ISSUE TITLE
Interested Adopting the Plugin

### ISSUE THREAD

**Issue by tareq1988** [tareq1988/wp-recaptcha-integration#92]
Hey @mcguffin,

As it seems like the plugin is being abandoned, is it possible that I can adopt the plugin? I couldn't find other ways to connect with you. So please let me know.

Here's my [org profile](https://profiles.wordpress.org/tareq1988/#content-plugins).

Thanks

**Comment by mcguffin** [comment]
Hi @tareq1988,

Thanks for your offer! (And a pretty impressive profile ;) )
I'll hand over the github repo and the wporg plugin to you later this week. 
There also is a [composer package](https://packagist.org/packages/mcguffin/wp-recaptcha-integration) on packagist.org. I have no idea how to transfer that one. Do you have more intel...?

It was not an easy decision. I abandoned the plugin mainly because I did no longer want to support googles (and others) aggressive data collection practices. As a coder I too often feel abused by them, copy-pasting their tracking gear and turning unsuspective web users into AI-food.

On the other hand there still is no working alternative as versatile as grecaptcha. Killing the plugin would break things for non-technical reasons.

**Comment by tareq1988** [comment]
Hello @mcguffin, Sorry for replying late. Thanks for the appreciation.

You are right, every big tech companies are evil. It's a long discussion we can do ;)

But it's a good plugin and I want to support it and plan to continue to remain it functional :)

**Comment by mcguffin** [comment]
Hi @tareq1988
I just started the transfer on wporg. It should be yours soon!
I tried to hand over the github repo as well, so we would have a proper redirect. 
It didn't work, there is a five years old fork in your namespace. Maybe you can you rename or delete it...?

**Comment by tareq1988** [comment]
I've deleted the repo, it should work now.

**Comment by mcguffin** [comment]
Yep, It worked! 
Best Regards & Happy coding!

**Comment by mcguffin** [comment]
Oops, one last thing: I just abandoned the [composer package](https://packagist.org/packages/mcguffin/wp-recaptcha-integration) and set `tareq1988/wp-recaptcha-integration` as a replacement. 
Please let me know if you prefer to drop support for installation via composer – I'll remove the replacement then.

**Comment by tareq1988** [comment]
You can remove the composer package :)
